// HEADER
export const SET_HEADER_LINKS = "SET_HEADER_LINKS";
export const SET_NAVBAR_LINKS = "SET_NAVBAR_LINKS";
export const CHANGE_NAVBAR_ACTIVE = "CHANGE_NAVBAR_ACTIVE";

// USER
export const SET_USER_PURCHASES = "SET_USER_PURCHASES";
export const SET_PURCHASE_DETAIL = "SET_PURCHASE_DETAIL";
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

// USER CART
export const SET_CART_PRODUCTS = "SET_CART_PRODUCTS";
export const ADD_CART_PRODUCT = "ADD_CART_PRODUCT";
export const DELETE_CART_PRODUCT = "DELETE_CART_PRODUCT";

// SHOP
export const SET_SHOP_CATEGORIES = "SET_SHOP_CATEGORIES";
export const SET_SHOP_PRODUCTS = "SET_SHOP_PRODUCTS";
export const SET_SHOP_APPLY_FILTER = "SET_SHOP_APPLY_FILTER";
export const FETCH_SHOP_FILTER_LISTS = "FETCH_SHOP_FILTER_LISTS";
export const FILTER_PRODUCTS_WITH_CATEGORY_ID = "FILTER_PRODUCTS_WITH_CATEGORY_ID";
export const FILTER_PRODUCTS_WITH_QUERY = "FILTER_PRODUCTS_WITH_QUERY";

// HOME PAGE
export const SET_HOME_PDF = "SET_HOME_PDF";
export const SET_RESOURCES = "SET_RESOURCES";
export const SET_LAB_NOTES = "SET_LAB_NOTES";
export const SET_HOME_EVENTS_RESOURCES = "SET_HOME_EVENTS_RESOURCES";

export const SET_SUB_NAV_CATEGORIES = "SET_SUB_NAV_CATEGORIES";
export const SET_SUB_NAV_LINKS = "SET_SUB_NAV_LINKS";
export const SET_SUB_HEADER_LINKS = "SET_SUB_HEADER_LINKS";
export const CHANGE_SUB_NAV_ACTIVE = "CHANGE_SUB_NAV_ACTIVE";

// FILTER OPTIONS
export const SET_FILTER_OPTIONS = "SET_FILTER_OPTIONS";

// PAGE
export const SET_PAGE_CSV = "SET_PAGE_CSV";

// BRANDS
export const FETCH_BRANDS = "FETCH_BRANDS";
export const FETCH_BRAND_CONTENT = "FETCH_BRAND_CONTENT";

export const FETCH_BULLETS = "FETCH_BULLETS";
export const FETCH_PHASE_IMAGE = "FETCH_PHASE_IMAGE";

// RESOURCES
export const FETCH_RESOURCES = "FETCH_RESOURCES";
export const FETCH_RESOURCES_CONTENT = "FETCH_RESOURCES_CONTENT";
export const SET_RESOURCE_DETAILS = "SET_RESOURCE_DETAILS";
export const FETCH_RESOURCES_FILTER_LIST = "FETCH_RESOURCES_FILTER_LIST";
export const SET_RESOURCES_APPLY_FILTER = "SET_RESOURCES_APPLY_FILTER";
export const SET_POSTER_PRESENTATIONS = "SET_POSTER_PRESENTATIONS";

// PROMOTIONS
export const FETCH_PROMOTIONS = "FETCH_PROMOTIONS";
export const FETCH_PROMOTIONS_CONTENT = "FETCH_PROMOTIONS_CONTENT";

// CONTACT US
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACT_DETAILS = "FETCH_CONTACT_DETAILS";

// PHASE PAGE IMAGE
export const SET_PHASE_PAGE_IMAGE = "SET_PHASE_PAGE_IMAGE";

export const SET_PHASE_PAGE_CONTENT = "SET_PHASE_PAGE_CONTENT";

// ORDERS
export const SET_ORDER_PLACED = "SET_ORDER_PLACED";
export const SET_RECENT_ORDERS = "SET_RECENT_ORDERS";
export const SET_ORDERED_ITEMS = "SET_ORDERED_ITEMS";

// CLICKED BUY NOW
export const CLICKED_BUY_NOW = "CLICKED_BUY_NOW";